### ISSUE TITLE
About 'K_stable.npy' and 'fullscale_rates.json'

### ISSUE THREAD

**Issue by ChenLumen** [INM-6/multi-area-model#30]
Hi, I don't konw how the 'K_stable.npy' and 'fullscale_rates.json' files were generated.  I guess the 'K_stable.npy' file were generated when ran the 'stabilization.py' file? But how did you create the another one?

**Comment by ChenLumen** [comment]
Hi, a bug appears when I run [this](https://github.com/INM-6/multi-area-model/blob/master/figures/SchueckerSchmidt2017/stabilization.py) file:

Traceback (most recent call last):
  File "/home/mingchenliu/workspace/Program/multi-area-model-master/figures/SchueckerSchmidt2017/stabilization.py", line 71, in <module>
    data[iteration] = utils.compute_iteration(7, fac_nu_ext_5E_list,
  File "/home/mingchenliu/workspace/Program/multi-area-model-master/figures/SchueckerSchmidt2017/utils.py", line 114, in compute_iteration
    results = np.vstack((results, r))
  File "<__array_function__ internals>", line 5, in vstack
  File "/home/mingchenliu/anaconda3/envs/my_nest/lib/python3.8/site-packages/numpy/core/shape_base.py", line 282, in vstack
    return _nx.concatenate(arrs, 0)
  File "<__array_function__ internals>", line 5, in concatenate
ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 2, the array at index 0 has size 3000 and the array at index 1 has size 3001

**Comment by jarsi** [comment]
Hi,
the K_stable.npy file was created, as you already pointed out, by running stabilization.py. I also run into the same error as you. I have to admit I am not really familiar with the stabilization method. I would assume that the error you posted is due to the wrong size of the results array, changing its size to
```
results = np.zeros((0, 254, int(theory_params['T'] / theory_params['dt'] + 1)))
```
looks reasonable and resolves this error for me. But after that I ran into an [assertion error](https://github.com/INM-6/multi-area-model/blob/2583232586d235594854842cb9a92a620ba2c93a/figures/SchueckerSchmidt2017/stabilization.py#L87). This certainly will need some more in depth analysis.

Considering the `fullscale_rates.json file`. I don't know how it was created. My guess would be that these are just rates extracted from a stable fullscale simulation.

**Comment by ChenLumen** [comment]
OK, I got it. But I got a wrong figure when I run SchueckerSchmidt2017/Fig7_stabilization_analysis.py. As my figure shown, the iteration_1 is stability before fac_nu_5E increased 1.07435, it's different from the result of your paper. Can you help me? @jarsi @AlexVanMeegen

![选区_022](https://user-images.githubusercontent.com/57821474/135019789-fafc840a-0256-4e43-a010-8e01898e8525.png)

I didn't plot iteration_5.

**Comment by ChenLumen** [comment]
I run the SchueckerSchmidt2017/stabilization.py file, no changed except @jarsi above said.

**Comment by jarsi** [comment]
I haven't run the script myself yet, but the figure that is [included in the repo](https://github.com/INM-6/multi-area-model/blob/master/figures/SchueckerSchmidt2017/Fig7_stabilization_analysis.eps) shows the same behavior you are describing. I don't know why this is the case and it certainly seems to wrong, but will look into it as soon as possible.

**Comment by ChenLumen** [comment]
> I haven't run the script myself yet, but the figure that is [included in the repo](https://github.com/INM-6/multi-area-model/blob/master/figures/SchueckerSchmidt2017/Fig7_stabilization_analysis.eps) shows the same behavior you are describing. I don't know why this is the case and it certainly seems to wrong, but will look into it as soon as possible.

OK, thanks. Please tell me what to do when you know how to solve it.

**Comment by ChenLumen** [comment]
Hi,  @jarsi @AlexVanMeegen. I want use the stabilitization method to my data. I found [this](https://datadryad.org/stash/dataset/doi:10.5061/dryad.vn342) in your paper, that looks the same as in your paper. Can you give me the code that generated this data about K_matrix? Or give me your parameters. I want to repeat your work, and then apply it to my data. Thank you very much!

**Comment by jarsi** [comment]
Hi, neither @AlexVanMeegen nor me were part of this publication. We are users and co-maintainers of the repo as it is related to our own work. I'll ask around whether we can get access to the original code or if someone has an idea what is missing here.
