### ISSUE TITLE
ImportError: No module named config

### ISSUE THREAD

**Issue by russelljjarvis** [INM-6/multi-area-model#32]
I am having trouble running the model because of a missing config module.
```
Traceback (most recent call last):
  File "../../multiarea_model/data_multiarea/VisualCortex_Data.py", line 83, in <module>
    from config import base_path
ImportError: No module named config
```
```
lambda-quad:~/multi-area-model$ python run_example_downscaled.py 
Traceback (most recent call last):
  File "run_example_downscaled.py", line 4, in <module>
    from multiarea_model import MultiAreaModel
  File "/home/russell/multi-area-model/multiarea_model/__init__.py", line 1, in <module>
    from . import default_params
  File "/home/russell/multi-area-model/multiarea_model/default_params.py", line 14, in <module>
    from config import base_path
ImportError: cannot import name base_path
```

**Comment by russelljjarvis** [comment]
Sorry I can see this is addressed in the README.md
